export const example = [
    {
      id: "1",
      title: "Sum and Product",
      difficulty: "Easy",
      successRate: 80,
      accpted: 1000,
      submissions: 2000,
      author: "Shadab",
      point: 10,
    },
    {
      id: "2",
      title: "Binary Search",
      difficulty: "Medium",
      successRate: 60,
      accpted: 800,
      submissions: 1000,
      author: "Shadab",
      point: 20,
    },
    {
      id: "3",
      title: "Dynamic Programming",
      difficulty: "Hard",
      successRate: 40,
      accpted: 60,
      submissions: 100,
      author: "unknowkubbrother",
      point: 30,
    },
    {
      id: "4",
      title: "Graph Traversal",
      difficulty: "Medium",
      successRate: 55,
      accpted: 500,
      submissions: 900,
      author: "Alice",
      point: 20,
    },
    {
      id: "5",
      title: "Sorting Algorithms",
      difficulty: "Easy",
      successRate: 75,
      accpted: 1200,
      submissions: 1600,
      author: "Bob",
      point: 10,
    },
    {
      id: "6",
      title: "Linked List",
      difficulty: "Easy",
      successRate: 85,
      accpted: 1500,
      submissions: 1800,
      author: "Charlie",
      point: 10,
    },
    {
      id: "7",
      title: "Tree Traversal",
      difficulty: "Medium",
      successRate: 65,
      accpted: 700,
      submissions: 1100,
      author: "David",
      point: 20,
    },
    {
      id: "8",
      title: "Hash Map",
      difficulty: "Easy",
      successRate: 90,
      accpted: 2000,
      submissions: 2200,
      author: "Eve",
      point: 10,
    },
    {
      id: "9",
      title: "Recursion",
      difficulty: "Hard",
      successRate: 35,
      accpted: 300,
      submissions: 800,
      author: "Frank",
      point: 30,
    },
    {
      id: "10",
      title: "Backtracking",
      difficulty: "Hard",
      successRate: 45,
      accpted: 400,
      submissions: 900,
      author: "Grace",
      point: 30,
    },
    {
      id: "11",
      title: "Greedy Algorithms",
      difficulty: "Medium",
      successRate: 50,
      accpted: 600,
      submissions: 1200,
      author: "Heidi",
      point: 20,
    },
    {
      id: "12",
      title: "Divide and Conquer",
      difficulty: "Medium",
      successRate: 58,
      accpted: 650,
      submissions: 1300,
      author: "Ivan",
      point: 20,
    },
    {
      id: "13",
      title: "Bit Manipulation",
      difficulty: "Hard",
      successRate: 30,
      accpted: 250,
      submissions: 700,
      author: "Judy",
      point: 30,
    },
    {
      id: "14",
      title: "String Matching",
      difficulty: "Easy",
      successRate: 78,
      accpted: 1100,
      submissions: 1400,
      author: "Mallory",
      point: 10,
    },
    {
      id: "15",
      title: "Matrix Operations",
      difficulty: "Medium",
      successRate: 60,
      accpted: 800,
      submissions: 1500,
      author: "Niaj",
      point: 20,
    },
    {
      id: "16",
      title: "Number Theory",
      difficulty: "Hard",
      successRate: 40,
      accpted: 350,
      submissions: 900,
      author: "Olivia",
      point: 30,
    },
    {
      id: "17",
      title: "Game Theory",
      difficulty: "Medium",
      successRate: 55,
      accpted: 500,
      submissions: 1000,
      author: "Peggy",
      point: 20,
    },
    {
      id: "18",
      title: "Computational Geometry",
      difficulty: "Hard",
      successRate: 38,
      accpted: 280,
      submissions: 800,
      author: "Sybil",
      point: 30,
    },
    {
      id: "19",
      title: "Network Flow",
      difficulty: "Hard",
      successRate: 42,
      accpted: 320,
      submissions: 850,
      author: "Trent",
      point: 30,
    },
    {
      id: "20",
      title: "Dynamic Connectivity",
      difficulty: "Medium",
      successRate: 57,
      accpted: 600,
      submissions: 1100,
      author: "Victor",
      point: 20,
    },
    {
        id: "21",
        title: "Shortest Path",
        difficulty: "Medium",
        successRate: 60,
        accpted: 700,
        submissions: 1200,
        author: "Walter",
        point: 20,
    },
    {
        id: "22",
        title: "Maximum Flow",
        difficulty: "Hard",
        successRate: 35,
        accpted: 300,
        submissions: 850,
        author: "Xander",
        point: 30,
    },
    {
        id: "23",
        title: "Minimum Spanning Tree",
        difficulty: "Medium",
        successRate: 55,
        accpted: 500,
        submissions: 1000,
        author: "Yvonne",
        point: 20,
    },
    {
        id: "24",
        title: "Knapsack Problem",
        difficulty: "Medium",
        successRate: 58,
        accpted: 650,
        submissions: 1300,
        author: "Zara",
        point: 20,
    },
    {
        id: "25",
        title: "Travelling Salesman",
        difficulty: "Hard",
        successRate: 30,
        accpted: 250,
        submissions: 700,
        author: "Aaron",
        point: 30,
    },
    {
        id: "26",
        title: "Eulerian Path",
        difficulty: "Medium",
        successRate: 60,
        accpted: 800,
        submissions: 1500,
        author: "Betty",
        point: 20,
    },
    {
        id: "27",
        title: "Hamiltonian Path",
        difficulty: "Hard",
        successRate: 40,
        accpted: 350,
        submissions: 900,
        author: "Cathy",
        point: 30,
    },
    {
        id: "28",
        title: "Graph Coloring",
        difficulty: "Medium",
        successRate: 55,
        accpted: 500,
        submissions: 1000,
        author: "Derek",
        point: 20,
    },
    {
        id: "29",
        title: "Strongly Connected Components",
        difficulty: "Hard",
        successRate: 38,
        accpted: 280,
        submissions: 800,
        author: "Ellen",
        point: 30,
    },
    {
        id: "30",
        title: "Articulation Points",
        difficulty: "Hard",
        successRate: 42,
        accpted: 320,
        submissions: 850,
        author: "Frank",
        point: 30,
    },
    {
        id: "31",
        title: "Bridge Finding",
        difficulty: "Medium",
        successRate: 57,
        accpted: 600,
        submissions: 1100,
        author: "Grace",
        point: 20,
    },
    {
        id: "32",
        title: "Bipartite Graph",
        difficulty: "Easy",
        successRate: 75,
        accpted: 1200,
        submissions: 1600,
        author: "Hank",
        point: 10,
    },
    {
        id: "33",
        title: "Topological Sort",
        difficulty: "Medium",
        successRate: 65,
        accpted: 700,
        submissions: 1100,
        author: "Ivy",
        point: 20,
    },
    {
        id: "34",
        title: "Bellman-Ford Algorithm",
        difficulty: "Hard",
        successRate: 30,
        accpted: 250,
        submissions: 700,
        author: "Jack",
        point: 30,
    },
    {
        id: "35",
        title: "Floyd-Warshall Algorithm",
        difficulty: "Medium",
        successRate: 60,
        accpted: 800,
        submissions: 1500,
        author: "Karen",
        point: 20,
    },
    {
        id: "36",
        title: "Dijkstra's Algorithm",
        difficulty: "Easy",
        successRate: 85,
        accpted: 1500,
        submissions: 1800,
        author: "Leo",
        point: 10,
    },
    {
        id: "37",
        title: "Prim's Algorithm",
        difficulty: "Medium",
        successRate: 65,
        accpted: 700,
        submissions: 1100,
        author: "Mona",
        point: 20,
    },
    {
        id: "38",
        title: "Kruskal's Algorithm",
        difficulty: "Medium",
        successRate: 55,
        accpted: 500,
        submissions: 1000,
        author: "Nate",
        point: 20,
    },
    {
        id: "39",
        title: "Ford-Fulkerson Algorithm",
        difficulty: "Hard",
        successRate: 35,
        accpted: 300,
        submissions: 850,
        author: "Oscar",
        point: 30,
    },
    {
        id: "40",
        title: "Edmonds-Karp Algorithm",
        difficulty: "Hard",
        successRate: 42,
        accpted: 320,
        submissions: 850,
        author: "Paul",
        point: 30,
    }
  ];