name: Checking

on: [push]

defaults:
  run:
    working-directory: ./client

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install bun dependencies
        run: bun install
      - name: Run ESLint
        run: bun run lint
