name: Checking

on: [push]

defaults:
  run:
    working-directory: ./client

jobs:
  checking:
    name: Checking Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4